UBUNTU: SAUCE: net: switchdev: fix compilation error for CONFIG_NET_SWITCHDEV=n
BugLink: https://bugs.launchpad.net/bugs/2104380

Since jammy:linux commit 0158242f01a0 ("net: bridge: switchdev: Skip MDB
replays of deferred events on offload"), the kernel build fails when
CONFIG_NET_SWITCHDEV=n, as observed in e.g. jammy:linux-kvm.

/build/jammy/net/bridge/br_mdb.c: In function 'br_mdb_queue_one':
/build/jammy/net/bridge/br_mdb.c:640:13: error: implicit declaration of function
'switchdev_port_obj_act_is_deferred'; did you mean 'switchdev_port_obj_add'? \
  [-Werror=implicit- function-declaration]

  640 |             switchdev_port_obj_act_is_deferred(dev, action, &mdb.obj)) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             switchdev_port_obj_add

Fix this by adding dummy switchdev_port_obj_act_is_deferred() for the
CONFIG_NET_SWITCHDEV=n case.

Fixes: 0158242f01a0 ("net: bridge: switchdev: Skip MDB replays of deferred events on offload") # jammy:linux
Signed-off-by: Koichiro Den <koichiro.den@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Acked-by: Massimiliano Pellizzer <massimiliano.pellizzer@canonical.com>
Acked-by: Andrei Gherzan <andrei.gherzan@canonical.com>
Signed-off-by: Mehmet Basaran <mehmet.basaran@canonical.com>