UBUNTU: SAUCE: (lockdown) security: lockdown: remove trailing semicolon before function body
BugLink: https://bugs.launchpad.net/bugs/1880660

A prior commit added security_lock_kernel_down for both CONFIG_SECURITY
and !CONFIG_SECURITY, but in an apparent copy and paste error, the
!CONFIG_SECURITY definition was added with a trailing semicolon before
the function body, causing compilation errors unearthed by
build.wireguard.com:

./include/linux/security.h:1277:1: error: expected identifier or ‘(’ before ‘{’ token
 1277 | {
      | ^
./include/linux/security.h:1276:19: warning: ‘security_lock_kernel_down’ declared ‘static’ but never defined [-Wunused-function]
 1276 | static inline int security_lock_kernel_down(const char *where, enum lockdown_reason level);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~

The solution is to simply remove the errant semicolon.

Fixes: 40fc208c8aae ("UBUNTU: SAUCE: (lockdown) security: lockdown: expose a hook to lock the kernel down")
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
(adjusted like 3af5459da853e8c49416d644ea219f334d25563c
 git://git.kernel.org/pub/scm/linux/kernel/git/jwboyer/fedora.git)
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Acked-by: Colin Ian King <colin.king@canonical.com>
Signed-off-by: Khalid Elmously <khalid.elmously@canonical.com>