ASoC: SOF: Intel: hda-dsp: fix compilation warning
BugLink: https://bugs.launchpad.net/bugs/1826181

sound/soc/sof/intel/hda-dsp.c: In function
‘hda_dsp_set_hw_params_upon_resume’:
sound/soc/sof/intel/hda-dsp.c:469:6: error: variable ‘stream_tag’ set
but not used [-Werror=unused-but-set-variable]
  int stream_tag;

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit add961d1dbc3b0f1a7d95dd63a0bfac8411371d8
git://github.com/thesofproject/linux.git)
Signed-off-by: Hui Wang <hui.wang@canonical.com>
Signed-off-by: Timo Aaltonen <timo.aaltonen@canonical.com>