iwlwifi: fix false-positive maybe-uninitialized warning
BugLink: https://bugs.launchpad.net/bugs/1809224

With CONFIG_NO_AUTO_INLINE, we run into a silly warning when
gcc fails to remember that n_profiles is constant across
the function call to iwl_mvm_sar_set_profile:

drivers/net/wireless/intel/iwlwifi/mvm/fw.c: In function 'iwl_mvm_sar_get_ewrd_table':
drivers/net/wireless/intel/iwlwifi/mvm/fw.c:746:9: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Marking that function 'inline' avoids the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
(cherry picked from commit e8698301f2c13ea4b0e78f2ed8a15b244ee3649b)
Signed-off-by: AceLan Kao <acelan.kao@canonical.com>
Signed-off-by: Timo Aaltonen <timo.aaltonen@canonical.com>